version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - mfilip
  assignees:
  - mfilip
  ignore:
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.20
    - 0.20.23
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.34
    - 14.14.35
  - dependency-name: semantic-release
    versions:
    - 17.4.2
  - dependency-name: typescript
    versions:
    - 4.2.4
  registries:
  - npm-registry-registry-npmjs-org
